### ISSUE TITLE
Document about running the code

### ISSUE THREAD

**Issue by Shawn-Hx** [xiangni/DREAM#1]
Hi,

Thanks for your great work!

I try to run this code by `python supervised_train.py` but the problem is:

```
Traceback (most recent call last):
  File "/home/huangxiao/gitProjects/DREAM/graphsage/supervised_train.py", line 240, in <module>
    tf.app.run()
  File "/home/huangxiao/gitProjects/DREAM/venv/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/huangxiao/gitProjects/DREAM/venv/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/huangxiao/gitProjects/DREAM/venv/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/huangxiao/gitProjects/DREAM/graphsage/supervised_train.py", line 235, in main
    train_data = load_data(FLAGS.train_prefix)
  File "/home/huangxiao/gitProjects/DREAM/graphsage/utils.py", line 79, in load_data
    G_data = json.load(open(prefix + "-adj.json"))
FileNotFoundError: [Errno 2] No such file or directory: '-adj.json'
```

It seems that there's no file whose name is "*-adj.json" in this repository. Could you provide the document about how to run this code?

**Comment by VegetablesBird6** [comment]
> Hi,
> 
> Thanks for your great work!
> 
> I try to run this code by `python supervised_train.py` but the problem is:
> 
> ```
> Traceback (most recent call last):
>   File "/home/huangxiao/gitProjects/DREAM/graphsage/supervised_train.py", line 240, in <module>
>     tf.app.run()
>   File "/home/huangxiao/gitProjects/DREAM/venv/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
>     _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
>   File "/home/huangxiao/gitProjects/DREAM/venv/lib/python3.7/site-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/home/huangxiao/gitProjects/DREAM/venv/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "/home/huangxiao/gitProjects/DREAM/graphsage/supervised_train.py", line 235, in main
>     train_data = load_data(FLAGS.train_prefix)
>   File "/home/huangxiao/gitProjects/DREAM/graphsage/utils.py", line 79, in load_data
>     G_data = json.load(open(prefix + "-adj.json"))
> FileNotFoundError: [Errno 2] No such file or directory: '-adj.json'
> ```
> 
> It seems that there's no file whose name is "*-adj.json" in this repository. Could you provide the document about how to run this code?





Do you run through the code？

**Comment by aditya1c** [comment]
GraphSAGE module can be run by downloading the original [GraphSAGE](https://github.com/williamleif/GraphSAGE) repo and using the following commands:

`python -m graphsage.supervised_train --train_prefix ./example_data/toy-ppi --model graphsage_mean --sigmoid`

`python -m graphsage.unsupervised_train --train_prefix ./example_data/toy-ppi --model graphsage_mean --max_total_steps 1000 --validate_iter 10
`

But the main controller_device.py file seems to have issues running. It would be nice if the authors can provide better documentation.

**Comment by wtian3913-cloud** [comment]
Hello, is this problem solved?
